version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo Hello 
  say-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo World! From Falay
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-world
         requires:
            - say-hello
