version: 2.1

commands: 
  print_pipeline_id:
    parameters:
      id:
        type: string
        default : "pipeline id"
    steps:
       -run : echo << parameters.id >>


jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "Hello World! From Falay" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  print_id:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id:
          id: ${CIRCLE_WORKFLOW_ID}
          
workflows:
  say-hello-workflow:
    jobs:
      - print_id
     